name: Deploy to Namecheap

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: false
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
      REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}
      REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Change to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/family-image-library
        chmod 600 ~/.ssh/family-image-library
        ssh-keyscan -H 198.54.125.112 >> ~/.ssh/known_hosts

    - name: Deploy build to Namecheap
      run: |
        rsync -avz --delete ./build/ cherhhvj@198.54.125.112:/home/cherhhvj/www/family-image-library