name: Deploy to Namecheap

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: false
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
      REACT_APP_GOOGLE_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_CLIENT_SECRET }}
      REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Change to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/family-image-library
        chmod 600 ~/.ssh/family-image-library
        ssh-keyscan -p 21098 198.54.125.112>> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        sshpass -p "${{ secrets.SSH_USER_PASSWORD }}" ssh -i ~/.ssh/family-image-library -p 21098 cherhhvj@198.54.125.112 'echo "SSH connection successful"'

    - name: Deploy build to Namecheap
      run: |
        sshpass -p "${{ secrets.SSH_USER_PASSWORD }}" rsync -avz --delete -e 'ssh -i ~/.ssh/family-image-library -p 21098' ./build/ cherhhvj@198.54.125.112:/home/cherhhvj/public_html/family-image-library

    - name: Upload .htaccess
      run: |
        sshpass -p "${{ secrets.SSH_USER_PASSWORD }}" scp -P 21098 -i ~/.ssh/family-image-library ./.htaccess cherhhvj@198.54.125.112:/home/cherhhvj/public_html/family-image-library/.htaccess
